version: '3.8'

networks:
  dev:

services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - dev

  web:
    build:
      context: .
    command:
      - uvicorn
      - main:app
      - --host
      - 127.0.0.1
      - --port
      - "8000"
      - --reload
    networks:
      - dev

volumes:
  postgres_data: