"""empty message

Revision ID: efd8be5335ed
Revises: 25e3e334a79e
Create Date: 2024-10-25 19:07:16.939107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd8be5335ed'
down_revision: Union[str, None] = '25e3e334a79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_title_key', 'book', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('book_title_key', 'book', ['title'])
    # ### end Alembic commands ###
